import typing

from BaseClasses import Entrance, Region
from worlds.kh3.Constants import *
from worlds.kh3.Locations import KingdomHeartsIIILocation

from worlds.kh3.GameData.OlympusLocationData import *
from worlds.kh3.GameData.MysteriousTowerLocationData import *
from worlds.kh3.GameData.TwilightTownLocationData import *
from worlds.kh3.GameData.HundredAcreWoodLocationData import *
from worlds.kh3.GameData.ToyBoxLocationData import *
from worlds.kh3.GameData.KingdomOfCoronaLocationData import *
from worlds.kh3.GameData.MonstropolisLocationData import *
from worlds.kh3.GameData.ArendelleLocationData import *
from worlds.kh3.GameData.CaribbeanLocationData import *
from worlds.kh3.GameData.SanFransokyoLocationData import *
from worlds.kh3.GameData.DarkWorldLocationData import *
from worlds.kh3.GameData.KeybladeGraveyardLocationData import *
from worlds.kh3.GameData.ScalaAdCaelumLocationData import *
from worlds.kh3.GameData.FinalWorldLocationData import *
from worlds.kh3.GameData.RadiantGardenLocationData import *
from worlds.kh3.GameData.QuadratumLocationData import *

class KingdomHeartsIIIRegion(Region):

    def __init__(self, name, hint, player, world):
        super().__init__(name, player, world, hint)

class KingdomHeartsIIIEntrance(Entrance): 
    game: str = KINGDOM_HEARTS_III

    def __init__(self, player, multiworld, name='', parent=None, connection_condition=False):
        super(KingdomHeartsIIIEntrance, self).__init__(player, name, parent)
        self.multiworld = multiworld
        self.connection_condition = connection_condition

def create_kh3_regions(player, multiworld, logic):
    regions = {}

    # Create regions
    for location in logic.location_list:
        name = location.name
        
        region = KingdomHeartsIIIRegion(name=name, hint='', player=player, world=multiworld)

        region.locations += [KingdomHeartsIIILocation(player, region, i) for i in location.items]
        regions[location] = region

    for kh3_location in logic.location_list:
        for connection_location, connection_condition in kh3_location.simple_connections + kh3_location.gated_connections:
            region_a = regions[kh3_location]
            region_b = regions[connection_location]

            entrance = KingdomHeartsIIIEntrance(
                player, multiworld, f"{region_a.name} -> {region_b.name}", region_a, connection_condition)
            region_a.exits.append(entrance)
            entrance.connect(region_b)

    return list(regions.values())

KH3_REGIONS: typing.Dict[str, typing.List[str]] = {
    MENU_REGION: [],
    KEYBLADE_CROSSROADS_REGION: [],

    OLYMPUS_RAVINE_REGION: OLYMPUS_RAVINE_LOCATIONS,
    OLYMPUS_CLIFF_ASCENT_REGION: OLYMPUS_CLIFF_ASCENT_LOCATIONS,
    OLYMPUS_MOUNTAINSIDE_REGION: OLYMPUS_MOUNTAINSIDE_LOCATIONS,
    OLYMPUS_SUMMIT_REGION: OLYMPUS_SUMMIT_LOCATIONS,
    OLYMPUS_ALLEYWAY_REGION: OLYMPUS_ALLEYWAY_LOCATIONS,
    OLYMPUS_AGORA_REGION: OLYMPUS_AGORA_LOCATIONS,
    OLYMPUS_THE_BIG_OLIVE_REGION: OLYMPUS_THE_BIG_OLIVE_LOCATIONS,
    OLYMPUS_GARDENS_REGION: OLYMPUS_GARDENS_LOCATIONS,
    OLYMPUS_OVERLOOK_REGION: OLYMPUS_OVERLOOK_LOCATIONS,
    OLYMPUS_COURTYARD_REGION: OLYMPUS_COURTYARD_LOCATIONS,
    OLYMPUS_CLOUD_RIDGE_REGION: OLYMPUS_CLOUD_RIDGE_LOCATIONS,
    OLYMPUS_CORRIDORS_REGION: OLYMPUS_CORRIDORS_LOCATIONS,
    OLYMPUS_BOSS_ARENA_REGION: OLYMPUS_BOSS_ARENA_LOCATIONS,

    MYSTERIOUS_TOWER_STUDY_REGION: MYSTERIOUS_TOWER_STUDY_LOCATIONS,

    TWILIGHT_TOWN_TRAM_COMMON_REGION: TWILIGHT_TOWN_TRAM_COMMON_LOCATIONS,
    TWILIGHT_TOWN_UNDERGROUND_CONDUIT_REGION: TWILIGHT_TOWN_UNDERGROUND_CONDUIT_LOCATIONS,
    TWILIGHT_TOWN_THE_WOODS_REGION: TWILIGHT_TOWN_THE_WOODS_LOCATIONS,
    TWILIGHT_TOWN_THE_OLD_MANSION_REGION: TWILIGHT_TOWN_THE_OLD_MANSION_LOCATIONS,

    HUNDRED_ACRE_WOOD_RABBITS_HOUSE_REGION: HUNDRED_ACRE_WOOD_RABBITS_HOUSE_LOCATIONS,

    TOY_BOX_ANDYS_HOUSE_REGION: TOY_BOX_ANDYS_HOUSE_LOCATIONS,
    TOY_BOX_MAIN_FLOOR_1F_REGION: TOY_BOX_MAIN_FLOOR_1F_LOCATIONS,
    TOY_BOX_MAIN_FLOOR_2F_REGION: TOY_BOX_MAIN_FLOOR_2F_LOCATIONS,
    TOY_BOX_MAIN_FLOOR_3F_REGION: TOY_BOX_MAIN_FLOOR_3F_LOCATIONS,
    TOY_BOX_ACTION_FIGURES_REGION: TOY_BOX_ACTION_FIGURES_LOCATIONS,
    TOY_BOX_LOWER_VENTS_REGION: TOY_BOX_LOWER_VENTS_LOCATIONS,
    TOY_BOX_BABIES_AND_TODDLERS_DOLLS_REGION: TOY_BOX_BABIES_AND_TODDLERS_DOLLS_LOCATIONS,
    TOY_BOX_VIDEO_GAMES_REGION: TOY_BOX_VIDEO_GAMES_LOCATIONS,
    TOY_BOX_KID_KORRAL_OUTDOORS_REGION: TOY_BOX_KID_KORRAL_OUTDOORS_LOCATIONS,
    TOY_BOX_KID_KORRAL_REGION: TOY_BOX_KID_KORRAL_LOCATIONS,
    TOY_BOX_REST_AREA_REGION: TOY_BOX_REST_AREA_LOCATIONS,
    TOY_BOX_BOSS_ARENA_REGION: TOY_BOX_BOSS_ARENA_LOCATIONS,

    KINGDOM_OF_CORONA_HILLS_REGION: KINGDOM_OF_CORONA_HILLS_LOCATIONS,
    KINGDOM_OF_CORONA_TOWER_REGION: KINGDOM_OF_CORONA_TOWER_LOCATIONS,
    KINGDOM_OF_CORONA_MARSH_REGION: KINGDOM_OF_CORONA_MARSH_LOCATIONS,
    KINGDOM_OF_CORONA_CAMPSITE_REGION: KINGDOM_OF_CORONA_CAMPSITE_LOCATIONS,
    KINGDOM_OF_CORONA_WETLANDS_REGION: KINGDOM_OF_CORONA_WETLANDS_LOCATIONS,
    KINGDOM_OF_CORONA_WILDFLOWER_CLEARING_REGION: KINGDOM_OF_CORONA_WILDFLOWER_CLEARING_LOCATIONS,
    KINGDOM_OF_CORONA_SHORE_REGION: KINGDOM_OF_CORONA_SHORE_LOCATIONS,
    KINGDOM_OF_CORONA_THOROUGHFARE_REGION: KINGDOM_OF_CORONA_THOROUGHFARE_LOCATIONS,
    KINGDOM_OF_CORONA_WHARF_REGION: KINGDOM_OF_CORONA_WHARF_LOCATIONS,

    MONSTROPOLIS_LOBBY_AND_OFFICES_REGION: MONSTROPOLIS_LOBBY_AND_OFFICES_LOCATIONS,
    MONSTROPOLIS_LAUGH_FLOOR_REGION: MONSTROPOLIS_LAUGH_FLOOR_LOCATIONS,
    MONSTROPOLIS_DOOR_VAULT_UPPER_LEVEL_REGION: MONSTROPOLIS_DOOR_VAULT_UPPER_LEVEL_LOCATIONS,
    MONSTROPOLIS_DOOR_VAULT_LOWER_LEVEL_REGION: MONSTROPOLIS_DOOR_VAULT_LOWER_LEVEL_LOCATIONS,
    MONSTROPOLIS_DOOR_VAULT_SERVICE_AREA_REGION: MONSTROPOLIS_DOOR_VAULT_SERVICE_AREA_LOCATIONS,
    MONSTROPOLIS_FACTORY_BASEMENT_REGION: MONSTROPOLIS_FACTORY_BASEMENT_LOCATIONS,
    MONSTROPOLIS_FACTORY_GROUND_FLOOR_REGION: MONSTROPOLIS_FACTORY_GROUND_FLOOR_LOCATIONS,
    MONSTROPOLIS_FACTORY_SECOND_FLOOR_REGION: MONSTROPOLIS_FACTORY_SECOND_FLOOR_LOCATIONS,
    MONSTROPOLIS_POWER_PLANT_ACCESSWAY_REGION: MONSTROPOLIS_POWER_PLANT_ACCESSWAY_LOCATIONS,
    MONSTROPOLIS_POWER_PLANT_TANK_YARD_REGION: MONSTROPOLIS_POWER_PLANT_TANK_YARD_LOCATIONS,
    MONSTROPOLIS_POWER_PLANT_VAULT_PASSAGE_REGION: MONSTROPOLIS_POWER_PLANT_VAULT_PASSAGE_LOCATIONS,

    ARENDELLE_TREESCAPE_REGION: ARENDELLE_TREESCAPE_LOCATIONS,
    ARENDELLE_THE_LABYRINTH_OF_ICE_LOWER_TIER_REGION: ARENDELLE_THE_LABYRINTH_OF_ICE_LOWER_TIER_LOCATIONS,
    ARENDELLE_THE_LABYRINTH_OF_ICE_MIDDLE_TIER_REGION: ARENDELLE_THE_LABYRINTH_OF_ICE_MIDDLE_TIER_LOCATIONS,
    ARENDELLE_THE_LABYRINTH_OF_ICE_UPPER_TIER_REGION: ARENDELLE_THE_LABYRINTH_OF_ICE_UPPER_TIER_LOCATIONS,
    ARENDELLE_GORGE_REGION: ARENDELLE_GORGE_LOCATIONS,
    ARENDELLE_FROZEN_WALL_REGION: ARENDELLE_FROZEN_WALL_LOCATIONS,
    ARENDELLE_VALLEY_OF_ICE_REGION: ARENDELLE_VALLEY_OF_ICE_LOCATIONS,
    ARENDELLE_SNOWFIELD_REGION: ARENDELLE_SNOWFIELD_LOCATIONS,
    ARENDELLE_FOOTHILLS_REGION: ARENDELLE_FOOTHILLS_LOCATIONS,
    ARENDELLE_SUMMIT_REGION: ARENDELLE_SUMMIT_LOCATIONS,
    ARENDELLE_MOUNTAINSIDE_REGION: ARENDELLE_MOUNTAINSIDE_LOCATIONS,
    ARENDELLE_MINI_BOSS_ARENA_REGION: ARENDELLE_MINI_BOSS_ARENA_LOCATIONS,
    ARENDELLE_BOSS_ARENA_REGION: ARENDELLE_BOSS_ARENA_LOCATIONS,

    THE_CARIBBEAN_DAVY_JONES_LOCKER_REGION: THE_CARIBBEAN_DAVY_JONES_LOCKER_LOCATIONS,
    THE_CARIBBEAN_THE_HIGH_SEAS_REGION: THE_CARIBBEAN_THE_HIGH_SEAS_LOCATIONS,
    THE_CARIBBEAN_ISLA_DE_LOS_MASTILES_REGION: THE_CARIBBEAN_ISLA_DE_LOS_MASTILES_LOCATIONS,
    THE_CARIBBEAN_SHIPS_END_REGION: THE_CARIBBEAN_SHIPS_END_LOCATIONS,
    THE_CARIBBEAN_SANDBAR_ISLE_REGION: THE_CARIBBEAN_SANDBAR_ISLE_LOCATIONS,
    THE_CARIBBEAN_HUDDLED_ISLES_REGION: THE_CARIBBEAN_HUDDLED_ISLES_LOCATIONS,
    THE_CARIBBEAN_LEVIATHAN_REGION: THE_CARIBBEAN_LEVIATHAN_LOCATIONS,
    THE_CARIBBEAN_PORT_ROYAL_SEAPORT_REGION: THE_CARIBBEAN_PORT_ROYAL_SEAPORT_LOCATIONS,
    THE_CARIBBEAN_PORT_ROYAL_DOCKS_REGION: THE_CARIBBEAN_PORT_ROYAL_DOCKS_LOCATIONS,
    THE_CARIBBEAN_PORT_ROYAL_SETTLEMENT_REGION: THE_CARIBBEAN_PORT_ROYAL_SETTLEMENT_LOCATIONS,
    THE_CARIBBEAN_PORT_ROYAL_FORT_REGION: THE_CARIBBEAN_PORT_ROYAL_FORT_LOCATIONS,
    THE_CARIBBEAN_PORT_ROYAL_WATERS_REGION: THE_CARIBBEAN_PORT_ROYAL_WATERS_LOCATIONS,
    THE_CARIBBEAN_ISLA_VERDEMONTANA_REGION: THE_CARIBBEAN_ISLA_VERDEMONTANA_LOCATIONS,
    THE_CARIBBEAN_EXILE_ISLAND_REGION: THE_CARIBBEAN_EXILE_ISLAND_LOCATIONS,
    THE_CARIBBEAN_CONFINEMENT_ISLE_REGION: THE_CARIBBEAN_CONFINEMENT_ISLE_LOCATIONS,
    THE_CARIBBEAN_HORSESHOE_ISLAND_REGION: THE_CARIBBEAN_HORSESHOE_ISLAND_LOCATIONS,
    THE_CARIBBEAN_BOSS_ARENA_REGION: THE_CARIBBEAN_BOSS_ARENA_LOCATIONS,

    SAN_FRANSOKYO_BRIDGE_REGION: SAN_FRANSOKYO_BRIDGE_LOCATIONS,
    SAN_FRANSOKYO_THE_CITY_NORTH_DISTRICT_REGION: SAN_FRANSOKYO_THE_CITY_NORTH_DISTRICT_LOCATIONS,
    SAN_FRANSOKYO_THE_CITY_SOUTH_DISTRICT_REGION: SAN_FRANSOKYO_THE_CITY_SOUTH_DISTRICT_LOCATIONS,
    SAN_FRANSOKYO_THE_CITY_CENTRAL_DISTRICT_REGION: SAN_FRANSOKYO_THE_CITY_CENTRAL_DISTRICT_LOCATIONS,

    DARK_WORLD_DARK_MARGIN_REGION: DARK_WORLD_DARK_MARGIN_LOCATIONS,

    KEYBLADE_GRAVEYARD_THE_BADLANDS_REGION: KEYBLADE_GRAVEYARD_THE_BADLANDS_LOCATIONS,
    KEYBLADE_GRAVEYARD_THE_SKEIN_OF_SEVERANCE_REGION: KEYBLADE_GRAVEYARD_THE_SKEIN_OF_SEVERANCE_LOCATIONS,

    SCALA_AD_CAELUM_THE_STAIRWAY_TO_THE_SKY_REGION: SCALA_AD_CAELUM_THE_STAIRWAY_TO_THE_SKY_LOCATIONS,
    SCALA_AD_CAELUM_BREEZY_QUARTER_REGION: SCALA_AD_CAELUM_BREEZY_QUARTER_LOCATIONS,
    SCALA_AD_CAELUM_BOSS_ARENA_REGION: [], # WIN CONDITION REGION
    SCALA_AD_CAELUM_DLC_BOSS_ARENA_REGION: [], # POTENTIALLY OTHER WIN CONDITION REGION?

    THE_FINAL_WORLD_THE_SEA_OF_STARS_REGION: THE_FINAL_WORLD_THE_SEA_OF_STARS_LOCATIONS,
    THE_FINAL_WORLD_LABYRINTH_OF_PILLARS_REGION: THE_FINAL_WORLD_LABYRINTH_OF_PILLARS_LOCATIONS,
    THE_FINAL_WORLD_FALLEN_SAN_FRANSOKYO_REGION: THE_FINAL_WORLD_FALLEN_SAN_FRANSOKYO_LOCATIONS,

    RADIANT_GARDEN_DATA_BATTLES_REGION: RADIANT_GARDEN_DATA_BATTLES_LOCATIONS,

    QUADRATUM_104_BUILDING_REGION: QUADRATUM_104_BUILDING_LOCATIONS,

    #END_SCREEN_REGION: END_SCREEN_LOCATIONS
}

KH3_REGION_CONNECTIONS: typing.Dict[str, typing.Tuple[str]] = {
    MENU_REGION: (KEYBLADE_CROSSROADS_REGION),

    #STATION_OF_AWAKENING_PLATFORM_REGION: (KEYBLADE_CROSSROADS_REGION),
    KEYBLADE_CROSSROADS_REGION: (OLYMPUS_CLIFF_ASCENT_REGION, TWILIGHT_TOWN_TRAM_COMMON_REGION,
                                 HUNDRED_ACRE_WOOD_RABBITS_HOUSE_REGION, TOY_BOX_ANDYS_HOUSE_REGION,
                                 KINGDOM_OF_CORONA_HILLS_REGION, MONSTROPOLIS_LOBBY_AND_OFFICES_REGION,
                                 ARENDELLE_TREESCAPE_REGION, THE_CARIBBEAN_DAVY_JONES_LOCKER_REGION,
                                 SAN_FRANSOKYO_BRIDGE_REGION, DARK_WORLD_DARK_MARGIN_REGION,
                                 KEYBLADE_GRAVEYARD_THE_BADLANDS_REGION, 
                                 SCALA_AD_CAELUM_THE_STAIRWAY_TO_THE_SKY_REGION,
                                 RADIANT_GARDEN_DATA_BATTLES_REGION, QUADRATUM_104_BUILDING_REGION),
    
    OLYMPUS_CLIFF_ASCENT_INITIAL_REGION: (OLYMPUS_AGORA_RUIN_REGION),
    OLYMPUS_AGORA_RUIN_REGION: (OLYMPUS_OVERLOOK_RUIN_REGION),
    OLYMPUS_OVERLOOK_RUIN_REGION: (OLYMPUS_GARDENS_RUIN_REGION),
    OLYMPUS_GARDENS_RUIN_REGION: (OLYMPUS_THE_BIG_OLIVE_RUIN_REGION),
    OLYMPUS_THE_BIG_OLIVE_RUIN_REGION: (OLYMPUS_ALLEYWAY_REGION),
    OLYMPUS_ALLEYWAY_REGION: (OLYMPUS_AGORA_GOLEM_REGION),
    OLYMPUS_AGORA_GOLEM_REGION: (OLYMPUS_RAVINE_REGION),
    OLYMPUS_RAVINE_REGION: (OLYMPUS_CLIFF_ASCENT_REGION),
    OLYMPUS_CLIFF_ASCENT_REGION: (OLYMPUS_MOUNTAINSIDE_REGION),
    OLYMPUS_MOUNTAINSIDE_REGION: (OLYMPUS_SUMMIT_REGION),
    OLYMPUS_SUMMIT_REGION: (OLYMPUS_COURTYARD_REGION),
    OLYMPUS_COURTYARD_REGION: (OLYMPUS_CORRIDORS_REGION),
    OLYMPUS_CORRIDORS_REGION: (OLYMPUS_CLOUD_RIDGE_REGION),
    OLYMPUS_CLOUD_RIDGE_REGION: (OLYMPUS_BOSS_ARENA_REGION),
    OLYMPUS_BOSS_ARENA_REGION: (MYSTERIOUS_TOWER_STUDY_REGION, OLYMPUS_AGORA_REGION),
    OLYMPUS_AGORA_REGION: (OLYMPUS_THE_BIG_OLIVE_REGION),
    OLYMPUS_THE_BIG_OLIVE_REGION: (OLYMPUS_GARDENS_REGION),
    OLYMPUS_GARDENS_REGION: (OLYMPUS_OVERLOOK_REGION),

    TWILIGHT_TOWN_TRAM_COMMON_REGION: (TWILIGHT_TOWN_UNDERGROUND_CONDUIT_REGION),
    TWILIGHT_TOWN_UNDERGROUND_CONDUIT_REGION: (TWILIGHT_TOWN_THE_WOODS_REGION),
    TWILIGHT_TOWN_THE_WOODS_REGION: (TWILIGHT_TOWN_THE_OLD_MANSION_REGION),

    TOY_BOX_ANDYS_HOUSE_REGION: (TOY_BOX_MAIN_FLOOR_1F_REGION),
    TOY_BOX_MAIN_FLOOR_1F_REGION: (TOY_BOX_MAIN_FLOOR_2F_REGION),
    TOY_BOX_MAIN_FLOOR_2F_REGION: (TOY_BOX_REST_AREA_REGION, TOY_BOX_ACTION_FIGURES_REGION),
    TOY_BOX_ACTION_FIGURES_REGION: (TOY_BOX_LOWER_VENTS_REGION),
    TOY_BOX_LOWER_VENTS_REGION: (TOY_BOX_BABIES_AND_TODDLERS_DOLLS_REGION),
    TOY_BOX_BABIES_AND_TODDLERS_DOLLS_REGION: (TOY_BOX_MAIN_FLOOR_3F_REGION),
    TOY_BOX_MAIN_FLOOR_3F_REGION: (TOY_BOX_VIDEO_GAMES_REGION, TOY_BOX_KID_KORRAL_OUTDOORS_REGION),
    TOY_BOX_KID_KORRAL_OUTDOORS_REGION: (TOY_BOX_KID_KORRAL_REGION),
    TOY_BOX_KID_KORRAL_REGION: (TOY_BOX_BOSS_ARENA_REGION),

    KINGDOM_OF_CORONA_HILLS_REGION: (KINGDOM_OF_CORONA_TOWER_REGION, KINGDOM_OF_CORONA_MARSH_REGION),
    KINGDOM_OF_CORONA_MARSH_REGION: (KINGDOM_OF_CORONA_WETLANDS_REGION),
    KINGDOM_OF_CORONA_WETLANDS_REGION: (KINGDOM_OF_CORONA_WILDFLOWER_CLEARING_REGION),
    KINGDOM_OF_CORONA_WILDFLOWER_CLEARING_REGION: (KINGDOM_OF_CORONA_SHORE_REGION),
    KINGDOM_OF_CORONA_SHORE_REGION: (KINGDOM_OF_CORONA_THOROUGHFARE_REGION),
    KINGDOM_OF_CORONA_THOROUGHFARE_REGION: (KINGDOM_OF_CORONA_WHARF_REGION),

    MONSTROPOLIS_LOBBY_AND_OFFICES_REGION: (MONSTROPOLIS_LAUGH_FLOOR_REGION),
    MONSTROPOLIS_LAUGH_FLOOR_REGION: (MONSTROPOLIS_DOOR_VAULT_UPPER_LEVEL_REGION),
    MONSTROPOLIS_DOOR_VAULT_UPPER_LEVEL_REGION: (MONSTROPOLIS_DOOR_VAULT_LOWER_LEVEL_REGION),
    MONSTROPOLIS_DOOR_VAULT_LOWER_LEVEL_REGION: (MONSTROPOLIS_FACTORY_GROUND_FLOOR_REGION),
    MONSTROPOLIS_FACTORY_GROUND_FLOOR_REGION: (MONSTROPOLIS_FACTORY_BASEMENT_REGION, MONSTROPOLIS_FACTORY_SECOND_FLOOR_REGION),
    MONSTROPOLIS_FACTORY_SECOND_FLOOR_REGION: (MONSTROPOLIS_POWER_PLANT_ACCESSWAY_REGION),
    MONSTROPOLIS_POWER_PLANT_ACCESSWAY_REGION: (MONSTROPOLIS_POWER_PLANT_TANK_YARD_REGION),
    MONSTROPOLIS_POWER_PLANT_TANK_YARD_REGION: (MONSTROPOLIS_POWER_PLANT_VAULT_PASSAGE_REGION),
    MONSTROPOLIS_POWER_PLANT_VAULT_PASSAGE_REGION: (MONSTROPOLIS_DOOR_VAULT_SERVICE_AREA_REGION),

    ARENDELLE_TREESCAPE_REGION: (ARENDELLE_GORGE_REGION),
    ARENDELLE_GORGE_REGION: (ARENDELLE_THE_LABYRINTH_OF_ICE_MIDDLE_TIER_REGION, ARENDELLE_FROZEN_WALL_REGION,
                             ARENDELLE_SUMMIT_REGION),
    ARENDELLE_THE_LABYRINTH_OF_ICE_MIDDLE_TIER_REGION: (ARENDELLE_THE_LABYRINTH_OF_ICE_LOWER_TIER_REGION,
                                                        ARENDELLE_THE_LABYRINTH_OF_ICE_UPPER_TIER_REGION),
    ARENDELLE_FROZEN_WALL_REGION: (ARENDELLE_VALLEY_OF_ICE_REGION),
    ARENDELLE_SUMMIT_REGION: (ARENDELLE_SNOWFIELD_REGION, ARENDELLE_MINI_BOSS_ARENA_REGION,
                              ARENDELLE_SNOWFIELD_REGION),
    ARENDELLE_SNOWFIELD_REGION: (ARENDELLE_FOOTHILLS_REGION),
    ARENDELLE_FOOTHILLS_REGION: (ARENDELLE_BOSS_ARENA_REGION),

    THE_CARIBBEAN_DAVY_JONES_LOCKER_REGION: (THE_CARIBBEAN_HUDDLED_ISLES_REGION),
    THE_CARIBBEAN_HUDDLED_ISLES_REGION: (THE_CARIBBEAN_THE_HIGH_SEAS_REGION),
    THE_CARIBBEAN_THE_HIGH_SEAS_REGION: (THE_CARIBBEAN_ISLA_DE_LOS_MASTILES_REGION, THE_CARIBBEAN_SHIPS_END_REGION,
                                         THE_CARIBBEAN_SANDBAR_ISLE_REGION, THE_CARIBBEAN_ISLA_VERDEMONTANA_REGION,
                                         THE_CARIBBEAN_EXILE_ISLAND_REGION, THE_CARIBBEAN_CONFINEMENT_ISLE_REGION,
                                         THE_CARIBBEAN_HORSESHOE_ISLAND_REGION, THE_CARIBBEAN_PORT_ROYAL_WATERS_REGION),
    THE_CARIBBEAN_PORT_ROYAL_WATERS_REGION: (THE_CARIBBEAN_LEVIATHAN_REGION, THE_CARIBBEAN_PORT_ROYAL_SEAPORT_REGION,
                                             THE_CARIBBEAN_BOSS_ARENA_REGION),
    THE_CARIBBEAN_PORT_ROYAL_SEAPORT_REGION: (THE_CARIBBEAN_PORT_ROYAL_DOCKS_REGION),
    THE_CARIBBEAN_PORT_ROYAL_DOCKS_REGION: (THE_CARIBBEAN_PORT_ROYAL_SETTLEMENT_REGION),
    THE_CARIBBEAN_PORT_ROYAL_SETTLEMENT_REGION: (THE_CARIBBEAN_PORT_ROYAL_FORT_REGION),

    SAN_FRANSOKYO_BRIDGE_REGION: (SAN_FRANSOKYO_THE_CITY_NORTH_DISTRICT_REGION, 
                                  SAN_FRANSOKYO_THE_CITY_CENTRAL_DISTRICT_REGION,
                                  SAN_FRANSOKYO_THE_CITY_SOUTH_DISTRICT_REGION),
    
    KEYBLADE_GRAVEYARD_THE_BADLANDS_REGION: (THE_FINAL_WORLD_THE_SEA_OF_STARS_REGION, KEYBLADE_GRAVEYARD_THE_SKEIN_OF_SEVERANCE_REGION,
                                             THE_FINAL_WORLD_FALLEN_SAN_FRANSOKYO_REGION),
    THE_FINAL_WORLD_THE_SEA_OF_STARS_REGION: (THE_FINAL_WORLD_LABYRINTH_OF_PILLARS_REGION),

    SCALA_AD_CAELUM_DLC_THE_STAIRWAY_TO_THE_SKY_REGION: (SCALA_AD_CAELUM_BREEZY_QUARTER_REGION),
    SCALA_AD_CAELUM_BREEZY_QUARTER_REGION: (SCALA_AD_CAELUM_DLC_BOSS_ARENA_REGION),

    SCALA_AD_CAELUM_THE_STAIRWAY_TO_THE_SKY_REGION: (SCALA_AD_CAELUM_BOSS_ARENA_REGION),
    SCALA_AD_CAELUM_BOSS_ARENA_REGION: (END_SCREEN_REGION)
}